// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsqqfoefpfmvpwofbmbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcXFmb2VmcGZtdnB3b2ZibWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDI0NzcsImV4cCI6MjA2NTQ3ODQ3N30.qcDbF6l_fzh605OfyM05d9z5J1OB3hlG6sCnv2sKeMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);